apiVersion: apps/v1
kind: Deployment
metadata:
  name: vedantrajkavi.dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vedantrajkavi.dev
  template:
    metadata:
      labels:
        app: vedantrajkavi.dev
    spec:
      containers:
      - name: vedantrajkavi.dev
        image: vedantrajkavi.dev
        ports:
        - containerPort: 80
