name: Deploy Astro to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Chromium for Puppeteer (for Astro OG image plugin)
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser

      - name: Add .nojekyll
        run: echo "" > dist/.nojekyll

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist